### ISSUE TITLE
Game pauses on different tab

### ISSUE THREAD

**Issue by knockoutdonkey** [invincible-elevator/sumo-chicken#59]
Fix so that the game continues to run regardless of which tab it is in.

**Comment by shelleywang** [comment]
According to the creator of Phaser, 

"There's not much you can do about this I'm afraid. The boolean [game.stage.disableVisibilityChange] controls if Phaser will still update when the browser fires a visibility change (i.e. giving focus to another app), but what happens when you change tab is different, it's the browser deciding to no longer fire requestAnimationFrame events, consequently pausing your game (even though Phaser itself never thinks it has paused, it just never gets its core loop called because rAf has been halted).

Not all browsers do this (although most do now it appears), and it sort of makes sense - it's just a waste of CPU / battery to keep stuff constantly running in a tab you can't even see. Even so, it's frustrating to not have any kind of say in it."

http://www.html5gamedevs.com/topic/10847-gamestagedisablevisibilitychange-not-working/

So instead, to fix the problem for us, my idea is introducing a 'Paused' state that the server detects. If the server sees that a socket hasn't sent a sync request in 2 seconds, maybe it changes the chicken to a paused state and other players can't see it.

**Comment by knockoutdonkey** [comment]
That's an awesome idea!
Let me finish working on getting the server to control the syncing with the players and then we can implement it.
